//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitBooks_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Message { get; set; }
    
        public virtual LibraryUser LibraryUser { get; set; }
    }
}
