//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitBooks_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string AddressIPUser { get; set; }
        public string AddressIPEmployee { get; set; }
    
        public virtual LibraryUser LibraryUser { get; set; }
        public virtual LibraryUser LibraryUser1 { get; set; }
    }
}
