//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitBooks_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewLibrary
    {
        public int ReviewLibraryID { get; set; }
        public int UserID { get; set; }
        public string ReviewText { get; set; }
        public int Stars { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual LibraryUser LibraryUser { get; set; }
        public virtual ReviewLibrary ReviewLibrary1 { get; set; }
        public virtual ReviewLibrary ReviewLibrary2 { get; set; }
    }
}
